#!/bin/bash
options="Run Exit"
select option in $options; do
	if [ "Run" = $option ]; then
		echo Hello World
		exit
	elif [ $option = "Exit" ]; then 
		echo Exiting now
		exit
	else 	
		echo error
	fi
done
